### ISSUE TITLE
Building Instructions

### ISSUE THREAD

**Issue by arashbm** [tetujin/aware-client-ios#2]
I tried building the app but I cannot find any app specific build instruction and Makefile only has documentation related instructions. I tried normal `pod install` and building in XCode but seems like the default build steps are not working as expected. So far:
1. File `ViewController.m` has the wrong path in build phases (it tries looking in `aware-client-ios/ViewController.m` while it should be looking at `aware-client-ios/AWARE/ViewController.m`)
2. Fixing first problem by manually editing build phases, it tries to proceed to link phase but it fails with: `ld: warning: directory not found for option '-L/Users/badiea1/aware-client-ios/build/Debug-iphoneos'` (I was building for simulator so it should have been looking for Debug-iphonesimulator i guess)
3. Solving that one (by removing directory from library search path) will make it fail with `duplicate symbol _notificationCallback` in `MDBluetoothManager.o` and `BluetoothScanner.o`.

So either I'm doing something completely wrong or the correct way to build is not just installing cocoapods and building in XCode.

**Comment by tetujin** [comment]
Hi @arashbm, 

Thank you for your reporting the error. I fixed the errors on the [new commit ](https://github.com/tetujin/aware-client-ios/commit/a47b8efeea20b226e6c68aec4d7338275c7f9099) based on your comment.

**(1)  ViewController.m's link error**
I modified the link for the ViewController on the master branch. I guess that when I merged a development branch, the link for the file was lost.

**(2) and (3) Compile error on a simulator** 
As you pointed out, the reason of the error is a method duplicate problem. I removed the -notificationCallback method from BluetoothScanner.m.

Thank you
Yuuki
