### ISSUE TITLE
Confusing failure message when wifi_only=True or charging_only=True and manual upload

### ISSUE THREAD

**Issue by rkdarst** [tetujin/aware-client-ios#9]
When wifi_only=True or charging_only=True, if you do a manual upload and those conditions are not met, you get a generic failure message, instead of something saying which condition is not true.  This was very confusing, and together with the next issue I am about to submit resulted in a lot of debugging.

I'd suggest either "manual upload" does not follow those conditions, or if the conditions are not met then have a special error message.  (Or else, the generic message could have "or upload conditions not met" to at least point out there could be other problems.

Thanks,

- Richard

**Comment by tetujin** [comment]
Dear Richard,

Thank you very much for your comment. Yes, your indicate is light.

I'll modify the action of the manual upload button as follows:
If a user pushes the button, AWARE uploads the data even if the onely_wifi=on and only_battery_chargning=on. 

Best,
Yuuki

**Comment by rkdarst** [comment]
Sounds good!  Thanks.

By the way, everything seems to be working with our projects and our server, so thanks for the good work.

**Comment by tetujin** [comment]
Hi @rkdarst 

I modified the manual data upload function. On the new version, we can execute a data upload even if the device only has mobile network and battery un-charging condition.

Best,
Yuuki

**Comment by rkdarst** [comment]
Thank you!
